
import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const supabase = createClient('https://vadohvwjoxghubceffpn.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhZG9odndqb3hnaHViY2VmZnBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzczMzQxMjksImV4cCI6MjA5MjkxMDEyOX0.hrO9FcE32tlw6fL0I6EFu1sLFpBq_k6QBJ-LJIsvk24');
const $ = id => document.getElementById(id);
let state={pacientes:[],profesionales:[],consultas:[],tipos:[],citas:[],bloqueos:[]};
const horas=[]; for(let h=9;h<=20;h++){for(let m of [0,10,20,30,40,50]){if(h===9&&m<30)continue;if(h===20&&m>30)continue;horas.push(`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`)}}
let weekStart=monday(new Date());
function iso(d){return d.toISOString().slice(0,10)} function monday(d){const x=new Date(d);const day=x.getDay()||7;x.setDate(x.getDate()-day+1);return x} function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x} function fmt(d){return d.toLocaleDateString('es-ES',{weekday:'short',day:'2-digit',month:'2-digit'})} function norm(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
async function loadAll(){const [pac,prof,cons,tipos,citas,bloq]=await Promise.all([supabase.from('pacientes').select('*').order('nombre'),supabase.from('profesionales').select('*').order('nombre'),supabase.from('consultas').select('*').order('nombre'),supabase.from('tipos_cita').select('*').order('nombre'),supabase.from('citas').select('*').order('fecha').order('hora'),supabase.from('bloqueos').select('*').order('fecha')]); for(const r of [pac,prof,cons,tipos,citas,bloq]) if(r.error) throw r.error; state={pacientes:pac.data||[],profesionales:prof.data||[],consultas:cons.data||[],tipos:tipos.data||[],citas:citas.data||[],bloqueos:bloq.data||[]}; renderAll()}
function fill(id,rows,label='nombre',extra=''){const el=$(id);if(!el)return;el.innerHTML=extra+rows.map(r=>`<option value="${r.id}">${r[label]}</option>`).join('')}
function paciente(id){return state.pacientes.find(p=>p.id===id)||{}} function prof(id){return state.profesionales.find(p=>p.id===id)||{}} function consulta(id){return state.consultas.find(c=>c.id===id)||{}} function tipo(id){return state.tipos.find(t=>t.id===id)||{}}
function renderAll(){fill('filterProfessional',state.profesionales,'nombre','<option value="">Todos</option>');fill('citaProfesional',state.profesionales);fill('citaConsulta',state.consultas);fill('citaTipo',state.tipos);fill('bloqProf',state.profesionales,'nombre','<option value="">Todos</option>');renderWeek();renderPatients();renderConfig();renderBloqueos();renderAvisos();renderInfo()}
function renderWeek(){const days=[0,1,2,3,4].map(n=>addDays(weekStart,n));const pf=$('filterProfessional').value;$('weekPicker').value=iso(weekStart);$('weekTitle').textContent=`Semana del ${days[0].toLocaleDateString('es-ES')} al ${days[4].toLocaleDateString('es-ES')}`;let html='<thead><tr><th>Hora</th>'+days.map(d=>`<th>${fmt(d)}</th>`).join('')+'</tr></thead><tbody>';for(const h of horas){html+=`<tr><td><b>${h}</b></td>`;for(const d of days){const date=iso(d);const citas=state.citas.filter(c=>c.fecha===date&&String(c.hora).slice(0,5)===h&&(!pf||c.profesional_id===pf));html+=`<td class="slot" data-date="${date}" data-hour="${h}">`;html+=citas.length?citas.map(c=>`<div class="appt" data-cita="${c.id}"><strong>${paciente(c.paciente_id).nombre||''}</strong><br><span>${prof(c.profesional_id).nombre||''}</span><br><span>${tipo(c.tipo_cita_id).nombre||''} · ${c.duracion_minutos} min</span><br><span class="badge">${c.estado}</span></div>`).join(''):'<span class="small">+ Añadir</span>';html+='</td>'}html+='</tr>'}html+='</tbody>';$('weekTable').innerHTML=html;document.querySelectorAll('.slot').forEach(td=>td.onclick=e=>{if(e.target.closest('.appt'))return;openCita({fecha:td.dataset.date,hora:td.dataset.hour})});document.querySelectorAll('.appt').forEach(el=>el.onclick=e=>{e.stopPropagation();openExistingCita(el.dataset.cita)})}
function renderPatients(){const q=norm($('buscarPaciente')?.value||'');const rows=state.pacientes.filter(p=>norm(`${p.nombre} ${p.telefono} ${p.email}`).includes(q));$('pacientesTable').innerHTML='<thead><tr><th>Nombre</th><th>Teléfono</th><th>Email</th></tr></thead><tbody>'+rows.map(p=>`<tr><td>${p.nombre}</td><td>${p.telefono||''}</td><td>${p.email||''}</td></tr>`).join('')+'</tbody>'}
function renderConfig(){$('profTable').innerHTML='<tbody>'+state.profesionales.map(p=>`<tr><td>${p.nombre}</td></tr>`).join('')+'</tbody>';$('consultaTable').innerHTML='<tbody>'+state.consultas.map(c=>`<tr><td>${c.nombre}</td></tr>`).join('')+'</tbody>';$('tipoTable').innerHTML='<tbody>'+state.tipos.map(t=>`<tr><td>${t.nombre}</td><td>${t.duracion_minutos}</td><td>${t.descripcion||''}</td></tr>`).join('')+'</tbody>'}
function renderBloqueos(){$('bloqTable').innerHTML='<thead><tr><th>Fecha</th><th>Profesional</th><th>Horario</th><th>Motivo</th></tr></thead><tbody>'+state.bloqueos.map(b=>`<tr><td>${b.fecha||''}</td><td>${b.todos_profesionales?'Todos':(prof(b.profesional_id).nombre||'')}</td><td>${String(b.hora_inicio||'').slice(0,5)} - ${String(b.hora_fin||'').slice(0,5)}</td><td>${b.motivo||''}</td></tr>`).join('')+'</tbody>'}
function renderAvisos(){const f=$('avisosFecha').value||iso(new Date());$('avisosFecha').value=f;const rows=state.citas.filter(c=>{const d=new Date(c.fecha+'T00:00:00');d.setDate(d.getDate()-2);return iso(d)===f});$('avisosTable').innerHTML='<thead><tr><th>Paciente</th><th>Contacto</th><th>Cita</th><th>Profesional</th><th>Acciones</th></tr></thead><tbody>'+rows.map(c=>{const p=paciente(c.paciente_id);const msg=encodeURIComponent(`Hola ${p.nombre||''}, le recordamos su cita en Ynea el día ${c.fecha} a las ${String(c.hora).slice(0,5)}.`);return `<tr><td>${p.nombre||''}</td><td>${p.telefono||''}<br>${p.email||''}</td><td>${c.fecha} ${String(c.hora).slice(0,5)}</td><td>${prof(c.profesional_id).nombre||''}</td><td><a href="mailto:${p.email||''}?subject=Recordatorio de cita&body=${msg}">Email</a> · <a href="sms:${p.telefono||''}?&body=${msg}">SMS</a></td></tr>`}).join('')+'</tbody>'}
function renderInfo(){const hoy=iso(new Date());const ch=state.citas.filter(c=>c.fecha===hoy);$('infoGrid').innerHTML=`<div class="card">Citas de hoy<br><b style="font-size:34px">${ch.length}</b></div><div class="card">Pacientes<br><b style="font-size:34px">${state.pacientes.length}</b></div><div class="card">Profesionales<br><b style="font-size:34px">${state.profesionales.length}</b></div><div class="card">Consultas<br><b style="font-size:34px">${state.consultas.length}</b></div>`}
function openCita(d={}){$('citaDialogTitle').textContent='Nueva cita';$('citaId').value='';$('citaFecha').value=d.fecha||iso(new Date());$('citaHora').value=d.hora||'09:30';$('citaDuracion').value='10';$('citaEstado').value='Pendiente';$('citaPacienteId').value='';$('citaPacienteSearch').value='';$('citaProfesional').value=state.profesionales[0]?.id||'';$('citaConsulta').value=state.consultas[0]?.id||'';$('citaTipo').value=state.tipos[0]?.id||'';$('citaObs').value='';$('deleteCita').style.display='none';applyTipoDuration();$('citaDialog').showModal()}
function openExistingCita(id){const c=state.citas.find(x=>x.id===id);if(!c)return;$('citaDialogTitle').textContent='Modificar cita';$('citaId').value=c.id;$('citaFecha').value=c.fecha;$('citaHora').value=String(c.hora).slice(0,5);$('citaDuracion').value=String(c.duracion_minutos||10);$('citaEstado').value=c.estado||'Pendiente';$('citaPacienteId').value=c.paciente_id;$('citaPacienteSearch').value=paciente(c.paciente_id).nombre||'';$('citaProfesional').value=c.profesional_id||'';$('citaConsulta').value=c.consulta_id||'';$('citaTipo').value=c.tipo_cita_id||'';$('citaObs').value=c.observaciones||'';$('deleteCita').style.display='inline-block';$('citaDialog').showModal()}
async function saveCita(){const row={fecha:$('citaFecha').value,hora:$('citaHora').value,duracion_minutos:Number($('citaDuracion').value),estado:$('citaEstado').value,paciente_id:$('citaPacienteId').value||null,profesional_id:$('citaProfesional').value||null,consulta_id:$('citaConsulta').value||null,tipo_cita_id:$('citaTipo').value||null,observaciones:$('citaObs').value||null};if(!row.paciente_id)return alert('Selecciona un paciente.');const id=$('citaId').value;const res=id?await supabase.from('citas').update(row).eq('id',id):await supabase.from('citas').insert(row);if(res.error)return alert(res.error.message);$('citaDialog').close();await loadAll()}
async function deleteCita(){const id=$('citaId').value;if(!id)return;if(!confirm('¿Eliminar esta cita?'))return;const res=await supabase.from('citas').delete().eq('id',id);if(res.error)return alert(res.error.message);$('citaDialog').close();await loadAll()}
async function insert(table,row){const res=await supabase.from(table).insert(row);if(res.error)return alert(res.error.message);await loadAll()}
function applyTipoDuration(){
  const tipoId = $('citaTipo')?.value;
  const t = state.tipos.find(x => x.id === tipoId);
  if(t && $('citaDuracion')){
    $('citaDuracion').value = String(t.duracion_minutos || 10);
  }
}

function setupEvents(){document.querySelectorAll('nav button').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('nav button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('main section').forEach(s=>s.classList.remove('active'));$(btn.dataset.view).classList.add('active');renderAll()});$('prevWeek').onclick=()=>{weekStart=addDays(weekStart,-7);renderWeek()};$('nextWeek').onclick=()=>{weekStart=addDays(weekStart,7);renderWeek()};$('todayWeek').onclick=()=>{weekStart=monday(new Date());renderWeek()};$('weekPicker').onchange=()=>{weekStart=monday(new Date($('weekPicker').value));renderWeek()};$('filterProfessional').onchange=renderWeek;$('savePaciente').onclick=()=>insert('pacientes',{nombre:$('pacNombre').value,telefono:$('pacTelefono').value,email:$('pacEmail').value,observaciones:$('pacObs').value});$('buscarPaciente').oninput=renderPatients;$('saveProfesional').onclick=()=>insert('profesionales',{nombre:$('profNombre').value});$('saveConsulta').onclick=()=>insert('consultas',{nombre:$('consultaNombre').value});$('saveTipo').onclick=()=>insert('tipos_cita',{nombre:$('tipoNombre').value,duracion_minutos:Number($('tipoDuracion').value),descripcion:$('tipoDescripcion').value});$('saveBloqueo').onclick=()=>insert('bloqueos',{profesional_id:$('bloqProf').value||null,todos_profesionales:!$('bloqProf').value,fecha:$('bloqFecha').value,hora_inicio:$('bloqInicio').value,hora_fin:$('bloqFin').value,motivo:$('bloqMotivo').value});$('saveCita').onclick=saveCita;$('deleteCita').onclick=deleteCita;$('cancelCita').onclick=()=>$('citaDialog').close();$('citaTipo').onchange=applyTipoDuration;$('citaPacienteSearch').oninput=()=>{const q=norm($('citaPacienteSearch').value);const rows=state.pacientes.filter(p=>norm(`${p.nombre} ${p.telefono} ${p.email}`).includes(q)).slice(0,10);$('pacienteResults').innerHTML=rows.map(p=>`<div class="searchItem" data-id="${p.id}"><strong>${p.nombre}</strong><br><span>${p.telefono||''} ${p.email||''}</span></div>`).join('');$('pacienteResults').style.display='block';document.querySelectorAll('.searchItem').forEach(item=>item.onclick=()=>{const p=state.pacientes.find(x=>x.id===item.dataset.id);$('citaPacienteId').value=p.id;$('citaPacienteSearch').value=p.nombre;$('pacienteResults').style.display='none'})};$('quickPaciente').onclick=async()=>{const nombre=prompt('Nombre del nuevo paciente');if(!nombre)return;const telefono=prompt('Teléfono')||'';const email=prompt('Email')||'';const res=await supabase.from('pacientes').insert({nombre,telefono,email}).select().single();if(res.error)return alert(res.error.message);state.pacientes.push(res.data);$('citaPacienteId').value=res.data.id;$('citaPacienteSearch').value=res.data.nombre};horas.forEach(h=>$('citaHora').insertAdjacentHTML('beforeend',`<option>${h}</option>`));$('avisosFecha').value=iso(new Date());$('bloqFecha').value=iso(new Date())}
setupEvents(); loadAll().catch(e=>alert('Error conectando con Supabase: '+e.message));
